name: fightiq
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy>=1.26
  - pandas>=2.2
  - scikit-learn>=1.4
  - lightgbm>=4.0
  - xgboost>=2.0
  - catboost>=1.2
  - statsmodels>=0.14
  - scipy>=1.11
  - mlflow>=2.14
  - hydra-core>=1.3
  - pyyaml>=6.0
  - matplotlib>=3.8
  - pip:
      - ray>=2.30
